Repository micronaut-projects/micronaut-project-template, pull requests merged in 2020-07, with the labels that each got.

#13 Dependency upgrades
  build.gradle
Labels: type: dependency-upgrade

#23 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#31 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#30 Remove Probot settings file
  .github/settings.yml
Labels: relates-to: build

#32 doc: add repository section
  src/main/docs/guide/repository.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
